version: '3.7'
services:
  projet:
    build:
      context : ./mvc/
      dockerfile : dockerfile
    container_name: Front_deploy_test
    volumes:
      - ./:/var/www
    tty: true
    ports:
      - "80:5000"
    restart : always
    networks:
      - app-network

    depends_on:
      - reversproxy
  #nginx server 
  reversproxy:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro:read only
    ports:
      - "4001:80"
    tty: true
    restart : always
    networks:
      - app-network

#Docker Networks
#connexion entre les conatainers
networks:

 app-network:

  driver: bridge



