version: '3.7'
services:
  projet:
    build:
      context : ./mvc/
      dockerfile : dockerfile
    container_name: Front_deploy_test
    expose:
     - "5000"
    volumes:
      - ./:/var/www
    tty: true
    restart : always
    depends_on:
     - reversproxy
    networks:
      - app-network
    
  #nginx server 
  reversproxy:
    image: nginx:alpine
   # build:
    #  context : ./nginx/
   #   dockerfile : dockerfile
    volumes:
      - ./:/var/www
      - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro:read only
    ports: 
      - "4000:80"
    tty: true
    restart : always
  
    networks:
      - app-network
    

#Docker Networks
#connexion entre les conatainers
networks:

 app-network:

  driver: bridge



