version: '3.7'
services:
  projet:
    build:
      context : ./mvc/
      dockerfile : dockerfile
    container_name: Front_deploy_test
    volumes:
      - ./:/var/www
    tty: true
    ports:
     - "80:5000"
    restart : always
    networks:
      - app-network

    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_deploy_test
    volumes:
       - ./:/var/www
       - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro:read only
    ports:
      - "4005:80"
    networks:
      - app-network
    restart : always
#Docker Networks
#connexion entre les conatainers
networks:

 app-network:

  driver: bridge



