version: '3.7'
services:
  projet:
    build:
      context : ./mvc/
      dockerfile : dockerfile
    container_name: Front_deploy_test
    volumes:
      - ./:/var/www
    tty: true
    expose :
      - "5000"
    restart : always
    networks:
      - app-network

    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_deploy_test
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "4000:80"
    networks:
      - app-network
    restart : always
#Docker Networks
#connexion entre les conatainers
networks:

 app-network:

  driver: bridge



