version: "3.7"
services:

#dotnet service
  frontend:
    build: 
       context : ./MVC/
       dockerfile : dockerfile
    container_name: app
    volumes:
       - ./:/var/www
    depends_on:
      - reversproxy
    tty: true        # docker run -t
    ports:
      - "80:5000"
   #  expose :
     #  - "5000"
    restart : always
    networks:
      - app-network

#nginx server 
  reversproxy:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - "./nginx.conf:/etc/nginx/nginx.conf:ro" #ro:read only
    ports:
      - "4001:80"
    tty: true
    restart : always
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

  